configuration: Release

version: 1.0.{build}

image: Visual Studio 2017

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/tachyon1337-mrxqao6t197e
  api_key:
    secure: 77VoJopJzeflBblhONXBNYwMWlQ4C1dAgaWjGXKfJgc=
  skip_symbols: false
  artifact: /.*\.nupkg/

